### ISSUE TITLE
Try a ViewModifier to apply the ColorScheme

### ISSUE THREAD

**Issue by junjie** [rizwankce/SwiftUIColorSchemeTest#1]
Thanks for the Medium post and this project. I found this while trying to find a way to keep my SwiftUI iOS 14 widget in dark/light, regardless of system appearance.

I initially thought `preferredContentStyle` would be appropriate, since it supported `nil` so I could also revert to automatic. However, I realised the style as applied by preferredContentStyle did not persist. My widget would initially be created in the style, then very shortly changed to follow system appearance.

Setting `environment` key allows it to persist. However, as you mentioned, it does not take `nil` to support automatic appearance switching.

In the end, I used a ViewModifier to achieve this. In case you're interested, here's the code:

```
struct PreferredColorSchemeModifier: ViewModifier {
	var colorScheme: ColorScheme?
	
	@ViewBuilder
	func body(content: Content) -> some View {
		if let colorScheme = colorScheme {
			content
				.environment(\.colorScheme, colorScheme)
		} else {
			content
		}
	}
}

extension View {
	func applyPreferredColorScheme(_ colorScheme: ColorScheme?) -> some View {
		self.modifier(PreferredColorSchemeModifier(colorScheme: colorScheme))
	}
}
```

I believe you if include the above, and replace `.preferredColorScheme(preferredColorScheme)` with `.applyPreferredColorScheme(preferredColorScheme)` it should achieve what you're looking for.

**Comment by rizwankce** [comment]
@junjie 👋 

Thanks for taking your time to let me know. I remember we did try to create a `ViewModifier` and it didn't work as expected. Anyway Im gonna give a try again.

**Comment by rizwankce** [comment]
@junjie 

Just checked out your solution and it seems to be working with latest Xcode 12. Thanks again for the solution. Im gonna update the code, README and give credits to you.

**Comment by junjie** [comment]
Great to know it works!

**Comment by rizwankce** [comment]
@junjie updated the code and README with credits. 👍

**Comment by theshiau** [comment]
Thanks, this method is useful. 👍

**Comment by joe-scotto** [comment]
This is not working when used in a Sheet that is currently presenting. Otherwise it works fine.
